### ISSUE TITLE
please write a README

### ISSUE THREAD

**Issue by thkoch2001** [dabrahams/initsplit#18]
I don't get it to work. I have emacs version 25.1.1 and a big old custom.el file which I now want to split out. This is my initsplit config:

```
 '(initsplit-customizations-alist
   (quote
    (("^haskell-.*$" "haskell.el" nil t)
     ("^ido-.*$" "ido.el" nil t))))
 '(initsplit-default-directory "~/.emacs.d/custom.d/")
 '(initsplit-pretty-print t)
```

I save customizations by clicking the "Apply and Save" button in the top level customization buffer or in the initsplit buffer or the ido buffer. But only the haskell.el gets written although I also have variables matching ido-.

Before I start to debug and file a better bugreport, it would help to have a README to know whether I installed and configured the initsplit.el correctly.

**Comment by dabrahams** [comment]
Sorry, I'm not maintaining this package anymore.
